### ISSUE TITLE
uh Arcaydian still showing b66 on 5G even tho the tmobile app shows n41? i thought it was fixed? 

### ISSUE THREAD

**Issue by hamhamfreak** [highvolt-dev/tmo-live-graph#18]
Also What Nodejs version 
is best to use? as thats never specifyed ? as the nodejs19 seems to not like the app? ![image](https://user-images.githubusercontent.com/9193367/208895352-1e4affca-b775-4725-aea5-d4d91150f096.png)

**Comment by hamhamfreak** [comment]
im just confused is all as the instructions never said which version if nodejs to use

**Comment by hamhamfreak** [comment]
@highvolt-dev

**Comment by hamhamfreak** [comment]
bump

**Comment by highvolt-dev** [comment]
@hamhamfreak I last tested with Node version v12.21.0
The problem is probably more likely due to a firmware update on the Arcadyan. I have a Nokia gateway and can only test against the Arcadyan by collaborating with other people such as yourself.

If you can post the JSON response you get from http://192.168.12.1/TMI/v1/gateway?get=all here I can test against the API responses your Arcadyan's firmware is providing.

**Comment by highvolt-dev** [comment]
This may be related to https://github.com/highvolt-dev/tmo-monitor/issues/64 - I should be able to verify if you provide the information from the link in my previous comment

**Comment by hamhamfreak** [comment]
> 

![Screenshot_54](https://user-images.githubusercontent.com/9193367/211740001-fea03140-e962-47dc-a1df-590ba83502c1.png)

**Comment by hamhamfreak** [comment]
this?

**Comment by highvolt-dev** [comment]
@hamhamfreak yes that was what I was looking for - thank you

**Comment by hamhamfreak** [comment]
> @hamhamfreak yes that was what I was looking for - thank you

Your welcome and uh should I downgrade  to that node version anyway cus of the variabilitys and what not or ignore them ? 
![Uploading RDT_20230112_1022327443276394236368074.gif…]()

**Comment by hamhamfreak** [comment]
> @hamhamfreak yes that was what I was looking for - thank you

should i ignore all the vurabiliutys ?  as this all showed up when installing the lastest version of npm 2 weeks ago 

![0ig056gbg17a1](https://user-images.githubusercontent.com/9193367/212151634-6409cf5d-7556-42e9-8716-0c8ddc0604fb.png)

**Comment by hamhamfreak** [comment]
> @hamhamfreak yes that was what I was looking for - thank you

is there anything else you need ? hope this is figured out soon to make sure its even giving me the right readings

**Comment by hamhamfreak** [comment]
@highvolt-dev  now its 1.00.18
![Screenshot_62](https://user-images.githubusercontent.com/9193367/215392656-129f1d26-dadc-406d-a31c-5950d334fd33.png)

**Comment by hamhamfreak** [comment]
@highvolt-dev hello?

**Comment by hamhamfreak** [comment]
@highvolt-dev  any luck

**Comment by highvolt-dev** [comment]
@hamhamfreak sorry, I only work on this project in my free time, so it can take a while. I have all the information I need from you to work on it. nodejs vulnerabilities are primarily a concern for internet-facing applications, and this project is only intended for use on your local area network. Hope to provide an update to you soon.

**Comment by hamhamfreak** [comment]
sweet

**Comment by hamhamfreak** [comment]
@highvolt-dev sweet and yes i posted the 1.00.18 as a few days after the .16 one i got .18 heh

**Comment by highvolt-dev** [comment]
@hamhamfreak I fixed the Arcadyan 5G band display bug you reported - thanks!

https://github.com/highvolt-dev/tmo-live-graph/releases/tag/v0.0.5
