### ISSUE TITLE
Unhandled Rejection (TypeError): secondary.bands is undefined When gateway loses 5g

### ISSUE THREAD

**Issue by hamhamfreak** [highvolt-dev/tmo-live-graph#20]
Whenever The gateway loses 5G it seems to trigger the error 
![image](https://user-images.githubusercontent.com/9193367/233726925-03902fa0-c8ef-44db-8a93-ff3b66dc13ec.png)

**Comment by highvolt-dev** [comment]
Thanks for reporting, @hamhamfreak

**Comment by highvolt-dev** [comment]
@hamhamfreak fixed - new release is out https://github.com/highvolt-dev/tmo-live-graph/releases/tag/v0.0.6
